#!/usr/bin/env python3

import argparse

import requests

from itertools import chain
from fpo import load_config, Entry

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--filename', '-f', default='config.yaml', type=argparse.FileType())

    args = parser.parse_args()
    data = load_config(args.filename)

    for entry in chain(data['cli']['plugins'], data['foreman']['plugins'], data['smart_proxy']['modules'], data['smart_proxy']['providers'], data['installer']['modules']):
        release_url = f'{entry.url}/raw/HEAD/.github/workflows/release.yml'
        print(release_url)
        release_file = requests.get(release_url)
        if release_file.ok:
          print(f'{entry.name} has a release action')
          if entry.release_action is not None and entry.release_action in release_file.text:
            print(f'{entry.name} uses the recommended release action')
        else:
          print(f'{entry.name} needs a release action')

if __name__ == '__main__':
    main()
