#!/usr/bin/env python3

from dataclasses import dataclass
from typing import Optional

import yaml

# OS-specific packages use this path
DEBIAN_RELEASE = 'bullseye'
PACKAGING_URL = 'https://github.com/theforeman/foreman-packaging'


@dataclass
class Entry:
    short_name: str
    name: str = None
    url: str = None
    github_org: str = 'theforeman'
    installer: bool = True

    def __post_init__(self):
        if not self.url:
            self.url = f'https://github.com/{self.github_org}/{self.name}'


class PuppetModule(Entry): # pylint: disable=too-few-public-methods
    def __post_init__(self):
        if not self.name:
            self.name = f'puppet-{self.short_name}'
        super().__post_init__()


@dataclass
class PackagedEntry(Entry):
    rpm: Optional[str] = None
    rpm_directory: str = 'plugins'
    deb: Optional[str] = None
    puppet_acceptance_tests: Optional[str] = None
    translations: Optional[str] = None

    def __post_init__(self):
        super().__post_init__()

        if self.rpm is True:
            self.rpm = f'rubygem-{self.name}'
        if self.deb is True:
            self.deb = f'ruby-{self.name.replace("_", "-")}'

        if self.translations is True:
            self.translations = f'https://www.transifex.com/foreman/foreman/{self.name}/'

    @property
    def rpm_url(self):
        if not self.rpm:
            return None
        return f'{PACKAGING_URL}/tree/rpm/develop/packages/{self.rpm_directory}/{self.rpm}'

    @property
    def deb_url(self):
        if not self.deb:
            return None
        return f'{PACKAGING_URL}/tree/deb/develop/plugins/{self.deb}'

    @property
    def puppet_module(self):
        return None  # implemented by a subclass

    @property
    def puppet_acceptance_tests_url(self):
        if not self.puppet_acceptance_tests:
            return None
        return f'https://github.com/theforeman/{self.puppet_module}/tree/master/spec/acceptance/{self.puppet_acceptance_tests}_spec.rb'  # pylint: disable=line-too-long


class ForemanPlugin(PackagedEntry):
    def __post_init__(self):
        if not self.name:
            self.name = f'foreman_{self.short_name}'
        super().__post_init__()

    @property
    def puppet_module(self):
        return 'puppet-foreman'


class SmartProxyPlugin(PackagedEntry): # pylint: disable=too-few-public-methods
    def __post_init__(self):
        if not self.name:
            self.name = f'smart_proxy_{self.short_name}'
        if self.deb is True:
            self.deb = self.name.replace("-", "_")
        if self.puppet_acceptance_tests is True:
            self.puppet_acceptance_tests = self.short_name
        super().__post_init__()

    @property
    def puppet_module(self):
        return 'puppet-foreman_proxy'

class HammerPlugin(PackagedEntry):
    def __post_init__(self):
        if not self.name:
            self.name = f'hammer_cli_{self.short_name}'
        if not self.url:
            # A lot of repos use dashes, unlike the gem name
            self.url = f'https://github.com/{self.github_org}/hammer-cli-{self.short_name.replace("_", "-")}'
        if self.deb is True:
            self.deb = self.name.replace("-", "_")
        if self.puppet_acceptance_tests is None:
            self.puppet_acceptance_tests = True
        super().__post_init__()

    @property
    def deb_url(self):
        if not self.deb:
            return None
        return f'{PACKAGING_URL}/tree/deb/develop/dependencies/{DEBIAN_RELEASE}/{self.deb}'

    @property
    def puppet_module(self):
        return 'puppet-foreman'

    @property
    def puppet_acceptance_tests_url(self):
        return f'https://github.com/theforeman/{self.puppet_module}/tree/master/spec/acceptance/foreman_cli_plugins_spec.rb'  # pylint: disable=line-too-long


def load_config():
    with open('config.yaml', encoding='UTF-8') as f: # pylint: disable=invalid-name
        data = yaml.safe_load(f)

    data['cli']['plugins'] = [HammerPlugin(short_name=plugin_id, **(plugin or {}))
      for plugin_id, plugin in data['cli']['plugins'].items()]

    data['foreman']['plugins'] = [ForemanPlugin(short_name=plugin_id, **(plugin or {}))
      for plugin_id, plugin in data['foreman']['plugins'].items()]

    data['smart_proxy']['modules'] = [SmartProxyPlugin(short_name=module_id, **(module or {}))
      for module_id, module in data['smart_proxy']['modules'].items()]

    data['smart_proxy']['providers'] = [SmartProxyPlugin(short_name=provider_id, **(provider or {}))
      for provider_id, provider in data['smart_proxy']['providers'].items()]

    data['installer']['modules'] = [PuppetModule(short_name=module_id, **(module or {}))
      for module_id, module in data['installer']['modules'].items()]

    return data


def markdown_link(label, url):
    return f'[{label}]({url})' if url else '—'


def print_markdown_table(entries):
    print('| Name | Installer | i18n | RPM | deb | Acceptance |')
    print('|-|-|-|-|-|-|')
    for entry in entries:
        columns = [
            markdown_link(entry.short_name, entry.url),
            "✅" if entry.installer else "❌",
            markdown_link('i18n', entry.translations),
            markdown_link('RPM', entry.rpm_url),
            markdown_link('deb', entry.deb_url),
            markdown_link('acceptance', entry.puppet_acceptance_tests_url),
        ]

        print(f'| {" | ".join(columns)} |')
    print()


def render_markdown(data):
    print('# [CLI](https://github.com/theforeman/hammer-cli)')
    print('## Plugins')
    print_markdown_table(data['cli']['plugins'])

    print('# [Foreman](https://github.com/theforeman/foreman)')
    print('## Plugins')
    print_markdown_table(data['foreman']['plugins'])

    print('# [Foreman Proxy](https://github.com/theforeman/smart-proxy)')

    print('## Modules')
    print_markdown_table(data['smart_proxy']['modules'])

    print('## Providers')
    print_markdown_table(data['smart_proxy']['providers'])

    print('# [Foreman Installer](https://github.com/theforeman/foreman-installer)')
    print('## Modules')
    for puppet_module in data['installer']['modules']:
        print(f'* {markdown_link(puppet_module.short_name, puppet_module.url)}')


def main():
    data = load_config()

    render_markdown(data)

if __name__ == '__main__':
    main()
