name: Build and Deploy docs to Pages

on:
  pull_request:
  push:
    branches: ['master']
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build docs
        run: make build
      - name: Upload site to GitHub cache
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
          retention-days: 1
          compression-level: 0

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download site from GitHub cache
        uses: actions/download-artifact@v5
        with:
          name: site
      - name: Set up Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
